# Generated by Django 2.0.3 on 2018-03-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180325_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompetitionEntry',
            new_name='EntryScore',
        ),
    ]
