# Generated by Django 2.0.3 on 2018-03-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180325_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='event',
        ),
        migrations.RemoveField(
            model_name='entryscore',
            name='competition',
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('contest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Contest')),
            ],
            bases=('events.contest',),
        ),
        migrations.CreateModel(
            name='SemiFinal',
            fields=[
                ('contest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Contest')),
                ('order', models.PositiveIntegerField()),
            ],
            bases=('events.contest',),
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.AddField(
            model_name='contest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='entryscore',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Contest'),
            preserve_default=False,
        ),
    ]
