# Generated by Django 2.0.3 on 2018-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180327_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='semifinal',
            name='progression_count',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
