# Generated by Django 2.0.3 on 2018-03-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180330_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalentry',
            options={'verbose_name_plural': 'final entries'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semientry',
            options={'verbose_name_plural': 'semi entries'},
        ),
    ]
