# Generated by Django 2.0.3 on 2018-04-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20180408_2124'),
        ('events', '0008_contest_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='spotify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.SpotifyMedia'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.YoutubeMedia'),
        ),
    ]
