# Generated by Django 2.0.3 on 2018-04-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_final_has_semi_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='semientry',
            name='progression',
            field=models.BooleanField(default=False),
        ),
    ]
