# Generated by Django 2.0.3 on 2018-04-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tippning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalbet',
            old_name='rank_bet',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='semibet',
            old_name='advance_bet',
            new_name='progress',
        ),
    ]
