# Generated by Django 2.0.3 on 2018-04-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tippning', '0002_auto_20180410_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semibet',
            old_name='progress',
            new_name='progression',
        ),
    ]
