# Generated by Django 2.0.3 on 2018-04-13 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_semientry_progression'),
        ('tippning', '0003_auto_20180410_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tippning.Score')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Final')),
            ],
            bases=('tippning.score',),
        ),
        migrations.CreateModel(
            name='SemiScore',
            fields=[
                ('score_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tippning.Score')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.SemiFinal')),
            ],
            bases=('tippning.score',),
        ),
        migrations.AddField(
            model_name='score',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
