# Generated by Django 2.0.3 on 2018-04-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippning', '0004_auto_20180413_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
