# Generated by Django 2.0.3 on 2018-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tippning', '0005_auto_20180413_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='points',
            field=models.FloatField(),
        ),
    ]
