# Generated by Django 2.0.3 on 2018-03-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='spotify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.SpotifyMedia'),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.YoutubeMedia'),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.SpotifyMedia'),
        ),
    ]
