# Generated by Django 2.0.3 on 2018-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20180324_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubemedia',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='youtubemedia',
            name='video_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
